services:
  masstransit_scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: masstransit_scheduler
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production