services:
  masstransit_scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: masstransit_scheduler
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - rabbitmq_rabbitmq_network

networks:
  rabbitmq_rabbitmq_network:
    external: true  # 🔹 Use the existing RabbitMQ network